colormap = {
    "Uniform": "red",

    "Exp3": "magenta",
    "Exp3 FID": "springgreen",
    "Exp3 LAD": "slateblue",
    "Exp3": "magenta",
    "Exp3 Heap": 'darkorange',

    "Exp31": "peru",
    "Exp31": "peru",
    "Exp31 Optimized": "mediumpurple",
    "FPL": "green",
    "FPL (hashing)": "lime",
    "FPL (toplog)": "mediumpurple",
    "FPL Unnormalized": "springgreen",

    "Tsallis-INF (IW)": "blue",
    "Tsallis (IW)": "blue",
    "Tsallis-INF (RV)": "mediumblue",
    "Tsallis (RV)": "mediumblue",
    "Cumulative loss sampling": "yellowgreen",
    "Tsallis (IW with optimisations)": "slateblue",
    "Tsallis (RV with optimisations)": "mediumpurple",
    "Tsallis (LTU)": "mediumpurple",
    "Tsallis (RV approx)": "springgreen",

    "QBL": "darkorange",

    "Exp3m": "teal",
    "Exp31m": "deepskyblue",
    "Exp31m_2": "cyan",
    "Exp3m_heap": "aqua",
    "Exp3m Heap": "aqua",
    "Exp3tor": "slateblue",
    "Exp3IXtor": "saddlebrown",
    "Exp3Light": "springgreen",
    "Exp3Light Heap": "yellowgreen",
    "Exp3Light.M Heap": "springgreen",
}
