colormap = {
    "Uniform": "red",

    "Exp3": "magenta",
    "Exp3 FID": "springgreen",
    "Exp3 LAD": "slateblue",
    "Exp3": "magenta",
    "Exp3 Heap": 'aqua',
    "Exp3_heap": 'aqua',

    "Exp31": "peru",
    "Exp31": "peru",
    "Exp31 Optimized": "mediumpurple",
    "FPL": "green",
    "FPL (hashing)": "lime",
    "FPL (toplog)": "mediumpurple",
    "FPL Unnormalized": "springgreen",

    "Tsallis-INF (IW)": "blue",
    "Tsallis (IW)": "blue",
    "Tsallis-INF (RV)": "mediumblue",
    "Tsallis (RV)": "mediumblue",
    "Cumulative loss sampling": "yellowgreen",
    "Tsallis (IW with optimisations)": "slateblue",
    "Tsallis (RV with optimisations)": "mediumpurple",
    "Tsallis (LTU)": "mediumpurple",
    "Tsallis (RV approx)": "springgreen",

    "QBL": "darkorange",

    "Exp3m": "teal",
    "Exp31m": "deepskyblue",
    "Exp31m_2": "cyan",
    "Exp3m_heap": "aqua",
    "Exp3m Heap": "aqua",
    "Exp3tor": "slateblue",
    "Exp3IXtor": "saddlebrown",
    "Exp3IXTor": "saddlebrown",
    "Exp3Light": "springgreen",
    "Exp3Light Heap": "yellowgreen",
    "Exp3LightHeap": "yellowgreen",
    "Exp3Light.M Heap": "springgreen",

    "UCB": "navy",
    "UCB1": "royalblue",
    "DEXP": "crimson",
    "RBA": "goldenrod",
    "Tsallis": "steelblue",
    "Tsallis-INF": "cornflowerblue",
    "Exp3m Light": "mediumseagreen",
    "Exp3mLight": "mediumseagreen",
    "Exp3m IX": "firebrick",
    "Exp3mIX": "firebrick",
}
